# Generated by Django 6.0 on 2025-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_points',
            field=models.TextField(blank=True, help_text='Écrire chaque point sur une nouvelle ligne'),
        ),
    ]
